---
title: "爛 code 收集器//空的 try，但是有寫 catch"
date: 2018-05-13T15:24:00.000+08:00
tags: 
- "爛 code 收集器"
categories:
- 舊部落格移植文章
---

# 爛 code 收集器//空的 try，但是有寫 catch

原文連結: https://darkblack02.blogspot.com/2018/05/code-try-catch.html
移植時的最後更新日期: 2020-02-28T10:41:21.456+08:00

任何程式碼的刪除或添加，都必須要順過「上下文」，之後的人讀 code 才不會有這種驚喜!!!  <pre class="prettyprint"><code class="language-cpp"><br />void FuBase::MessageReceived(<br />    string ChannelId, string MessageId, XmlElement &Data )<br />{<br />  try<br />  {<br />  }<br />  catch( std::exception & e )<br />  {<br />    log2File("Occur Exception at [" +string( __FUNC__) + "] : " + string(e .what()) );<br />    log2File("[File: " + string( __FILE__) + "] (Line: " + IntToStr (__LINE__) + " )", detail );<br />  }<br />  catch ( Exception& e )<br />  {<br />    log2File("Occur Exception at [" +string( __FUNC__) + "] : " + string(e .Message. c_str()) );<br />    log2File("[File: " + string( __FILE__) + "] (Line: " + IntToStr (__LINE__) + " )", detail );<br />  }<br />  catch(...)<br />  {<br />    log2File("Occur exception at [" +string( __FUNC__) + "]" );<br />    log2File("[File: " + string( __FILE__) + "] (Line: " + IntToStr (__LINE__) + " )", detail );<br />  }<br />}<br /></code></pre>無聲的聲音： 這是希望可以寫log嗎？ 
